[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "filewatcher123d"
version = "0.1.0"
description = "A tool to watch a file and run it in a persistent, auto-reloading IPython kernel with ocp_vscode."
readme = "README.md"
requires-python = ">=3.11,<3.15"

dependencies = [
    "jupyter-client",
    "jupyter-console",
    "watchdog",
    "ipykernel",
    "build123d",
    "ocp-viewer>=1.1.3",
]

# This creates the 'fw123d' command
[project.scripts]
fw123d = "filewatcher123d.cli:main"
